"""Add activity model

Revision ID: 207fa9c318e3
Revises: 2be36e2b72ac
Create Date: 2025-02-07 15:45:43.944412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207fa9c318e3'
down_revision = '2be36e2b72ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('fk_activities_destination_id_destinations')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    # ### end Alembic commands ###
